### ISSUE TITLE
Validation: Rule out presence of duplicate data for an observation entry

### ISSUE THREAD

**Issue by MatthewAlmeida** [MatthewAlmeida/CS682ActivityRecognitionTF#2] opened 2018-02-22 21:12 UTC
Validation step:  There are some files that have dates in the filenames.  We should determine if these are simply a different naming convention or are meant to distinguish data that exists in multiple files for the same subject.  This could cause duplication or incorrect association of data to subject when building the data tensors.

Short Version:  determine if files with dates in the filenames must be treated differently than those without.

**Comment by aovladi** [comment] 2018-03-05 00:20
I checked those files. The only problem was with one entry, where the extra file as a result was a duplicate of another file, so I put the extra file to removed directory. So no we can treat them equally.

**Closed** 2018-04-03 14:43 UTC
Labels: help wanted
